<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;

class UserTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testUserWithoutEmail()
    {
        $response = $this->post(route("storeUser"), [
            "name" => "Unit Test",
            "username" => "ut",
            "password" => "secure",
            "password_confirmation" => "secure"
        ]);

        $user = User::query()->where("name", "=", "Unit Test")->first();

        $this->assertNotNull($user);
        $response->assertRedirect(route("profile", compact("user")));
    }

    public function testUserWithEmail()
    {
        $response = $this->post(route("storeUser"), [
            "name" => "Unit Test 2",
            "username" => "ut2",
            "email" => "test@unit.de",
            "password" => "secure",
            "password_confirmation" => "secure"
        ]);

        $user = User::query()->where("name", "=", "Unit Test 2")->first();

        $this->assertNotNull($user);
        $response->assertRedirect(route("profile", compact("user")));
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->be(User::find(1));
    }
}
